ssfmb_cordearticle:
    path:     /cordearticle
    defaults: { _controller: SSFMBBundle:Corde:cordeArticle}

ssfmb_nombrecordearticle:
    path:     /nombrecordearticle
    defaults: { _controller: SSFMBBundle:Corde:nombreCordeArticle}