docslines:
    path:     /
    defaults: { _controller: "SSFMBBundle:DocsLines:index" }

docslines_show:
    path:     /{id}/show
    defaults: { _controller: "SSFMBBundle:DocsLines:show" }

docslines_new:
    path:     /new
    defaults: { _controller: "SSFMBBundle:DocsLines:new" }

docslines_create:
    path:     /create
    defaults: { _controller: "SSFMBBundle:DocsLines:create" }
    methods:  POST

docslines_edit:
    path:     /{id}/edit
    defaults: { _controller: "SSFMBBundle:DocsLines:edit" }

docslines_update:
    path:     /{id}/update
    defaults: { _controller: "SSFMBBundle:DocsLines:update" }
    methods:  [POST, PUT]

docslines_delete:
    path:     /{id}/delete
    defaults: { _controller: "SSFMBBundle:DocsLines:delete" }
    methods:  [POST, DELETE]
