emplacement:
    path:     /
    defaults: { _controller: "SSFMBBundle:Emplacement:index" }

emplacement_show:
    path:     /{id}/show
    defaults: { _controller: "SSFMBBundle:Emplacement:show" }

emplacement_new:
    path:     /new
    defaults: { _controller: "SSFMBBundle:Emplacement:new" }

emplacement_create:
    path:     /create
    defaults: { _controller: "SSFMBBundle:Emplacement:create" }
    methods:  POST

emplacement_edit:
    path:     /{id}/edit
    defaults: { _controller: "SSFMBBundle:Emplacement:edit" }

emplacement_update:
    path:     /{id}/update
    defaults: { _controller: "SSFMBBundle:Emplacement:update" }
    methods:  [POST, PUT]

emplacement_delete:
    path:     /{id}/delete
    defaults: { _controller: "SSFMBBundle:Emplacement:delete" }
    methods:  [POST, DELETE]
