flotteur:
    path:     /
    defaults: { _controller: "SSFMBBundle:Flotteur:index" }

flotteur_show:
    path:     /{id}/show
    defaults: { _controller: "SSFMBBundle:Flotteur:show" }

flotteur_new:
    path:     /new
    defaults: { _controller: "SSFMBBundle:Flotteur:new" }

flotteur_create:
    path:     /create
    defaults: { _controller: "SSFMBBundle:Flotteur:create" }
    methods:  POST

flotteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "SSFMBBundle:Flotteur:edit" }

flotteur_update:
    path:     /{id}/update
    defaults: { _controller: "SSFMBBundle:Flotteur:update" }
    methods:  [POST, PUT]

flotteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "SSFMBBundle:Flotteur:delete" }
    methods:  [POST, DELETE]
