lot:
    path:     /
    defaults: { _controller: "SSFMBBundle:Lot:index" }

lot_show:
    path:     /{id}/show
    defaults: { _controller: "SSFMBBundle:Lot:show" }

lot_new:
    path:     /new
    defaults: { _controller: "SSFMBBundle:Lot:new" }

lot_create:
    path:     /create
    defaults: { _controller: "SSFMBBundle:Lot:create" }
    methods:  POST

lot_edit:
    path:     /{id}/edit
    defaults: { _controller: "SSFMBBundle:Lot:edit" }

lot_update:
    path:     /{id}/update
    defaults: { _controller: "SSFMBBundle:Lot:update" }
    methods:  [POST, PUT]

lot_delete:
    path:     /{id}/delete
    defaults: { _controller: "SSFMBBundle:Lot:delete" }
    methods:  [POST, DELETE]
