ssfmb_parcstock:
    path:     /parcstock
    defaults: { _controller: SSFMBBundle:Magasins:parcStocks }
ssfmb_parclanterne:
    path:     /parclanterne
    defaults: { _controller: SSFMBBundle:Magasins:parcLanternes }
ssfmb_parccorde:
    path:     /parccorde
    defaults: { _controller: SSFMBBundle:Magasins:parccordes }
ssfmb_parcpoche:
    path:     /parcpoche
    defaults: { _controller: SSFMBBundle:Magasins:parcpoches }


magasins:
    path:     /
    defaults: { _controller: "SSFMBBundle:Magasins:index" }

magasins_show:
    path:     /{id}/show
    defaults: { _controller: "SSFMBBundle:Magasins:show" }

magasins_new:
    path:     /new
    defaults: { _controller: "SSFMBBundle:Magasins:new" }

magasins_create:
    path:     /create
    defaults: { _controller: "SSFMBBundle:Magasins:create" }
    methods:  POST

magasins_edit:
    path:     /{id}/edit
    defaults: { _controller: "SSFMBBundle:Magasins:edit" }

magasins_update:
    path:     /{id}/update
    defaults: { _controller: "SSFMBBundle:Magasins:update" }
    methods:  [POST, PUT]

magasins_delete:
    path:     /{id}/delete
    defaults: { _controller: "SSFMBBundle:Magasins:delete" }
    methods:  [POST, DELETE]
