parc:
    path:     /
    defaults: { _controller: "SSFMBBundle:Parc:index" }

parc_show:
    path:     /{id}/show
    defaults: { _controller: "SSFMBBundle:Parc:show" }

parc_new:
    path:     /new
    defaults: { _controller: "SSFMBBundle:Parc:new" }

parc_create:
    path:     /create
    defaults: { _controller: "SSFMBBundle:Parc:create" }
    methods:  POST

parc_edit:
    path:     /{id}/edit
    defaults: { _controller: "SSFMBBundle:Parc:edit" }

parc_update:
    path:     /{id}/update
    defaults: { _controller: "SSFMBBundle:Parc:update" }
    methods:  [POST, PUT]

parc_delete:
    path:     /{id}/delete
    defaults: { _controller: "SSFMBBundle:Parc:delete" }
    methods:  [POST, DELETE]
