ssegment:
    path:     /
    defaults: { _controller: "SSFMBBundle:SSegment:index" }

ssegment_show:
    path:     /{id}/show
    defaults: { _controller: "SSFMBBundle:SSegment:show" }

ssegment_new:
    path:     /new
    defaults: { _controller: "SSFMBBundle:SSegment:new" }

ssegment_create:
    path:     /create
    defaults: { _controller: "SSFMBBundle:SSegment:create" }
    methods:  POST

ssegment_edit:
    path:     /{id}/edit
    defaults: { _controller: "SSFMBBundle:SSegment:edit" }

ssegment_update:
    path:     /{id}/update
    defaults: { _controller: "SSFMBBundle:SSegment:update" }
    methods:  [POST, PUT]

ssegment_delete:
    path:     /{id}/delete
    defaults: { _controller: "SSFMBBundle:SSegment:delete" }
    methods:  [POST, DELETE]
