stocksarticles:
    path:     /
    defaults: { _controller: "SSFMBBundle:StocksArticles:index" }

stocksarticles_show:
    path:     /{id}/show
    defaults: { _controller: "SSFMBBundle:StocksArticles:show" }

stocksarticles_new:
    path:     /new
    defaults: { _controller: "SSFMBBundle:StocksArticles:new" }

stocksarticles_create:
    path:     /create
    defaults: { _controller: "SSFMBBundle:StocksArticles:create" }
    methods:  POST

stocksarticles_edit:
    path:     /{id}/edit
    defaults: { _controller: "SSFMBBundle:StocksArticles:edit" }

stocksarticles_update:
    path:     /{id}/update
    defaults: { _controller: "SSFMBBundle:StocksArticles:update" }
    methods:  [POST, PUT]

stocksarticles_delete:
    path:     /{id}/delete
    defaults: { _controller: "SSFMBBundle:StocksArticles:delete" }
    methods:  [POST, DELETE]
