stockage:
    path:     /
    defaults: { _controller: "SSFMBBundle:Stockage:index" }

stockage_show:
    path:     /{id}/show
    defaults: { _controller: "SSFMBBundle:Stockage:show" }

stockage_new:
    path:     /new
    defaults: { _controller: "SSFMBBundle:Stockage:new" }

stockage_create:
    path:     /create
    defaults: { _controller: "SSFMBBundle:Stockage:create" }
    methods:  POST

stockage_edit:
    path:     /{id}/edit
    defaults: { _controller: "SSFMBBundle:Stockage:edit" }

stockage_update:
    path:     /{id}/update
    defaults: { _controller: "SSFMBBundle:Stockage:update" }
    methods:  [POST, PUT]

stockage_delete:
    path:     /{id}/delete
    defaults: { _controller: "SSFMBBundle:Stockage:delete" }
    methods:  [POST, DELETE]
