<?php

namespace SS\FMBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcRepository extends EntityRepository
{
}
