<?php

namespace SS\FMBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SegmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegmentRepository extends EntityRepository
{
}
