<?php

namespace SS\FMBBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CordeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CordeRepository extends EntityRepository
{
    public function getDistinctQteCorde($ida)
    {
        $q = $this->_em->createQuery("SELECT e FROM SSFMBBundle:Corde e");
        $q->setParameter('ida', $ida);

        return $q->getResult();
    }
}
