<?php

namespace SS\FMBBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SS\FMBBundle\Entity\Magasins;

/**
 * EmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementRepository extends EntityRepository
{
    public function getTotaleEmplacementDuParc(Magasins $parc)
    {
        $qb = $this->createQueryBuilder('e')
            ->select('fi.nomFiliere,s.nomSegment,fl.nomFlotteur,e.place')
            ->join('e.flotteur', 'fl')->join('fl.segment', 's')->join('s.filiere', 'fi')
            ->where('fi.parc = :parc')
            ->andWhere('e.flotteur = fl.id, fl.segment = s.id , s.filiere=fi.id')
            ->groupBy('e.flotteur.id')
            ->setParameter('parc', $parc);
        return $qb->getQuery()->getResult();
    }
}
