<?php

namespace SS\FMBBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanterneRepository extends EntityRepository
{
    public function lanternePreparerYellowWarning(){

    }
    public function lanternePreparerRedWarning(){

    }
    public function lanternePGGreenWarning(){

    }
    public function lanternePGYellowWarning(){

    }
    public function lanternePGRedWarning(){

    }

}
