<?php

namespace SS\FMBBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcRepository extends EntityRepository
{
    public function findAllParc()
    {
        $qb = $this->createQueryBuilder('m')
            ->select(array('m.idMagasin', 'm.abrevMagasin'));
        return $qb->getQuery()->getResult();
    }

}
