<?php

namespace SS\FMBBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SS\FMBBundle\Entity\Article;
use SS\FMBBundle\Entity\Lot;

/**
 * StockageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockageRepository extends EntityRepository
{
    public function existe(Article $article, Lot $nlot)
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.article = :article')
            ->andWhere('s.nLot = :nlot')
            ->setParameter('article', $article)
            ->setParameter('nlot', $nlot);

        return $qb->getQuery()->getResult();
    }
}
