<?php

namespace SS\FMBBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StocksLanternesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StocksCordesRepository extends EntityRepository
{
    public function getCordePreparer($stocksArticlesSn, $corde)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.pret = false')
            ->andWhere('c.emplacement IS NULL')
            ->join('c.article', 's')
            ->addSelect('s')
            ->andwhere('s.refStockArticle = ?1')
            ->setParameter(1, $stocksArticlesSn->getRefStockArticle())
            ->andWhere('s.numeroSerie = ?2')
            ->setParameter(2, $stocksArticlesSn->getNumeroSerie())
            ->andWhere('c.corde = ?3')
            ->setParameter(3, $corde);
        return $qb->getQuery()->getResult();
    }

    public function getCordePreparerYellowWarning($parc)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('corde.nomCorde')
            ->addSelect('article.libArticle')
            ->addSelect('stocksarticlessn.numeroSerie')
            ->addSelect('c.dateDeCreation')
            ->addSelect('c.quantiter')
            ->join('c.article', 'stocksarticlessn')
            ->join('c.corde', 'corde')
            ->join('stocksarticlessn.refStockArticle', 'stocksarticle')
            ->join('stocksarticle.refArticle', 'article')
            ->where('corde.parc = :parc')
            ->andWhere('c.dateDeCreation = :date')
            ->andWhere('c.pret = :pret')
            ->andWhere('c.emplacement IS NULL')
            ->setParameter('date', new \DateTime(Date('Y-m-d')))
            ->setParameter('pret', false)
        ->setParameter('parc', $parc);
        return $qb->getQuery()->getResult();
    }

    public function getCordePreparerRedWarning($parc)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('corde.nomCorde')
            ->addSelect('article.libArticle')
            ->addSelect('stocksarticlessn.numeroSerie')
            ->addSelect('c.dateDeCreation')
            ->addSelect('c.quantiter')
            ->join('c.article', 'stocksarticlessn')
            ->join('c.corde', 'corde')
            ->join('stocksarticlessn.refStockArticle', 'stocksarticle')
            ->join('stocksarticle.refArticle', 'article')
            ->where('corde.parc = :parc')
            ->andWhere('c.dateDeCreation < :date')
            ->andWhere('c.emplacement IS NULL')
            ->andWhere('c.pret = :pret')
            ->setParameter('date', new \DateTime(Date('Y-m-d')))
            ->setParameter('pret', false)
            ->setParameter('parc', $parc);
        return $qb->getQuery()->getResult();
    }
}
