<?php

namespace SS\FMBBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StocksPochesBSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StocksPochesBSRepository extends EntityRepository
{
    public function getPochePreparer($stocksArticlesSn, $poche)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.pret = false')
            ->andWhere('p.emplacement IS NULL')
            ->join('p.article', 's')
            ->addSelect('s')
            ->andwhere('s.refStockArticle = ?1')
            ->setParameter(1, $stocksArticlesSn->getRefStockArticle())
            ->andWhere('s.numeroSerie = ?2')
            ->setParameter(2, $stocksArticlesSn->getNumeroSerie())
            ->andWhere('p.pochesbs = ?3')
            ->setParameter(3, $poche);
        return $qb->getQuery()->getResult();
    }
}
