<?php

namespace SS\FMBBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StocksLanternesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StocksCordesRepository extends EntityRepository
{
    public function getCordePreparer($stocksArticlesSn, $corde)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.pret = false')
            ->andWhere('c.emplacement IS NULL')
            ->join('c.article', 's')
            ->addSelect('s')
            ->andwhere('s.refStockArticle = ?1')
            ->setParameter(1, $stocksArticlesSn->getRefStockArticle())
            ->andWhere('s.numeroSerie = ?2')
            ->setParameter(2, $stocksArticlesSn->getNumeroSerie())
            ->andWhere('c.corde = ?3')
            ->setParameter(3, $corde);
        return $qb->getQuery()->getResult();
    }
}
