services:
    sonata.admin.parc:
          class: SS\FMBBundle\Admin\ParcAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, label: "Parc"}
          arguments:
              - ~
              - SS\FMBBundle\Entity\Parc
              - ~
          calls:
              - [ setTranslationDomain, [AcmeDemoBundle]]

    sonata.admin.filiere:
          class: SS\FMBBundle\Admin\FiliereAdmin
          tags:
              - { name: sonata.admin, manager_type: orm,group: "filiere",  label: "Filiere",label_catalogue: "Filiere" }
          arguments:
              - ~
              - SS\FMBBundle\Entity\Filiere
              - 'SonataAdminBundle:CRUD'
              - ~
          calls:
              - [ setTranslationDomain, [AcmeDemoBundle]]

    sonata.admin.segment:
          class: SS\FMBBundle\Admin\SegmentAdmin
          tags:
              - { name: sonata.admin, manager_type: orm,group: "filiere",  label: "Segment",label_catalogue: "Filiere" }
          arguments:
              - ~
              - SS\FMBBundle\Entity\Segment
              - 'SonataAdminBundle:CRUD'
              - ~
          calls:
              - [ setTranslationDomain, [AcmeDemoBundle]]

    sonata.admin.articles:
              class: SS\FMBBundle\Admin\ArticlesAdmin
              tags:
                  - { name: sonata.admin, manager_type: orm, label: "Article" }
              arguments:
                  - ~
                  - SS\FMBBundle\Entity\Articles
                  - ~
              calls:
                  - [ setTranslationDomain, [AcmeDemoBundle]]
    sonata.admin.lanterne:
              class: SS\FMBBundle\Admin\LanterneAdmin
              tags:
                  - { name: sonata.admin, manager_type: orm, group: "Lanterne", label: "Lanterne",label_catalogue: "Lanterne" }
              arguments:
                  - ~
                  - SS\FMBBundle\Entity\Lanterne
                  - ~
              calls:
                  - [ setTranslationDomain, [AcmeDemoBundle]]
    sonata.admin.poche:
          class: SS\FMBBundle\Admin\PocheAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Lanterne", label: "Poche",label_catalogue: "Poche" }
          arguments:
              - ~
              - SS\FMBBundle\Entity\Poche
              - ~
          calls:
              - [ setTranslationDomain, [AcmeDemoBundle]]
