services:
    sonata.admin.adresses:
        class: SS\FMBBundle\Admin\AdressesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Adresse"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\Adresses
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.adressesTypes:
        class: SS\FMBBundle\Admin\AdressesTypesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Adresse Types"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\AdressesTypes
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.annuaire:
        class: SS\FMBBundle\Admin\AnnuaireAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Annuaire"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\Annuaire
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.annuairecategories:
        class: SS\FMBBundle\Admin\AnnuaireCategoriesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Annuaire Categories"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\AnnuaireCategories
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.artcategsspecificites:
        class: SS\FMBBundle\Admin\ArtCategsSpecificitesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Art Categs Specificites"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\ArtCategsSpecificites
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.articles:
        class: SS\FMBBundle\Admin\ArticlesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Article"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\Articles
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.articlesvalorisations:
        class: SS\FMBBundle\Admin\ArticlesValorisationsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Articles Valorisations"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\ArticlesValorisations
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.civilites:
        class: SS\FMBBundle\Admin\CivilitesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Civilites"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\Civilites
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.corde:
        class: SS\FMBBundle\Admin\CordeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Stock",  label: "corde",label_catalogue: "Corde" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\Corde
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.docslines:
        class: SS\FMBBundle\Admin\DocsLinesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Document",  label: "DocsLines",label_catalogue: "DocsLines" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\DocsLines
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.docslinessn:
        class: SS\FMBBundle\Admin\DocsLinesSnAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Document",  label: "DocsLinesSn",label_catalogue: "DocsLinesSn" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\DocsLinesSn
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.documents:
        class: SS\FMBBundle\Admin\DocumentsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Document",  label: "Documents",label_catalogue: "Docuemnts" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\Documents
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

    sonata.admin.documentsetats:
        class: SS\FMBBundle\Admin\DocumentsEtatsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Document",  label: "DocumentsEtats",label_catalogue: "DocumentsEtats" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\DocumentsEtats
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.documentstypes:
        class: SS\FMBBundle\Admin\DocumentsTypesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Document",  label: "DocumentsTypes",label_catalogue: "DocumentsTypes" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\DocumentsTypes
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

    sonata.admin.emplacement:
        class: SS\FMBBundle\Admin\EmplacementAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "filiere",  label: "Emplacement",label_catalogue: "Filiere" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\Emplacement
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.filiere:
        class: SS\FMBBundle\Admin\FiliereAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "filiere",  label: "Filiere",label_catalogue: "Filiere" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\Filiere
            - 'SonataAdminBundle:CRUD'
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.flotteur:
        class: SS\FMBBundle\Admin\FlotteurAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "filiere",  label: "flotteur",label_catalogue: "Flotteur" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\Flotteur
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

    sonata.admin.lanterne:
        class: SS\FMBBundle\Admin\LanterneAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Stock", label: "Lanterne",label_catalogue: "Lanterne" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\Lanterne
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.magasins:
        class: SS\FMBBundle\Admin\MagasinsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Parc"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\Magasins
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.magasinsenseignes:
        class: SS\FMBBundle\Admin\MagasinsEnseignesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Magasins Enseignes"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\MagasinsEnseignes
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.pays:
        class: SS\FMBBundle\Admin\PaysAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Pays"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\Pays
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.pdfmodeles:
        class: SS\FMBBundle\Admin\PdfModelesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Pdf Modeles"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\PdfModeles
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.pdftypes:
        class: SS\FMBBundle\Admin\PdfTypesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Pdf Types"}
        arguments:
            - ~
            - SS\FMBBundle\Entity\PdfTypes
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

    sonata.admin.poche:
        class: SS\FMBBundle\Admin\PocheAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Stock", label: "Poche",label_catalogue: "Lanterne" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\Poche
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

    sonata.admin.segment:
        class: SS\FMBBundle\Admin\SegmentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "filiere",  label: "Segment",label_catalogue: "Segment" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\Segment
            - 'SonataAdminBundle:CRUD'
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

    sonata.admin.stocks:
        class: SS\FMBBundle\Admin\StocksAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Stock",  label: "stock",label_catalogue: "Stock" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\Stocks
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

    sonata.admin.stockarticle:
        class: SS\FMBBundle\Admin\StocksArticlesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Stock",  label: "stockarticle",label_catalogue: "StocksArticles" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\StocksArticles
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]
    sonata.admin.stocksarticlessn:
        class: SS\FMBBundle\Admin\StocksArticlesSnAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Stock",  label: "stockarticleSn",label_catalogue: "StocksArticlesSn" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\StocksArticlesSn
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

    sonata.admin.stockscorde:
        class: SS\FMBBundle\Admin\StocksCordeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Stock",  label: "stockcorde",label_catalogue: "StocksCorde" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\StocksCordes
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

    sonata.admin.stocklanterne:
        class: SS\FMBBundle\Admin\StocksLanternesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Stock",  label: "stocklanterne",label_catalogue: "StocksLanternes" }
        arguments:
            - ~
            - SS\FMBBundle\Entity\StocksLanternes
            - ~
        calls:
            - [ setTranslationDomain, [SSFMBBundle]]

