ssfmb_poche:
    resource: "@SSFMBBundle/Resources/config/routing/poche.yml"
    prefix:   /poche

ssfmb_lanterne:
    resource: "@SSFMBBundle/Resources/config/routing/lanterne.yml"
    prefix:   /lanterne

ssfmb_stockage:
    resource: "@SSFMBBundle/Resources/config/routing/stockage.yml"
    prefix:   /stockage

ssfmb_corde:
    resource: "@SSFMBBundle/Resources/config/routing/corde.yml"
    prefix:   /corde

ssfmb_ssegment:
    resource: "@SSFMBBundle/Resources/config/routing/ssegment.yml"
    prefix:   /ssegment

ssfmb_segment:
    resource: "@SSFMBBundle/Resources/config/routing/segment.yml"
    prefix:   /segment

ssfmb_filiere:
    resource: "@SSFMBBundle/Resources/config/routing/filiere.yml"
    prefix:   /filiere

ssfmb_parc:
    resource: "@SSFMBBundle/Resources/config/routing/parc.yml"
    prefix:   /parc

ssfmb_parc:
    resource: "@SSFMBBundle/Resources/config/routing/default.yml"
    prefix:   /

